### ISSUE TITLE
code doesn't work. APIs are not supported.

### ISSUE THREAD

**Issue by gustavkkk** [jingtum/jingtum-examples#3]
I tried the code, but it doesn't work. It is said that there is no such a attributes
setServer,setFinGate,

>>>fingate = FinGate()
##################################################################
>>> fingate.setServer(api_address, is_https, web_socket_address, api_version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'FinGate' object has no attribute 'setServer'
###################################################################
>>> fingate.setFinGate(test_address, test_secret)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'FinGate' object has no attribute 'setFinGate'
##################################################################
>>> ret = wallet.getBalance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jingtumsdk/account.py", line 408, in getBalance
    ret = self.get(url, parameters)
  File "/usr/local/lib/python2.7/dist-packages/jingtumsdk/account.py", line 68, in get
    return self.api_helper.get(url, para)
  File "/usr/local/lib/python2.7/dist-packages/jingtumsdk/server.py", line 123, in get
    raise JingtumRESTException(error_object)
jingtumsdk.server.JingtumRESTException: {
  "success": false,
  "error_type": "transaction",
  "error": "actNotFound",
  "message": "Account not found."
}

**Comment by gustavkkk** [comment]
setServer,setFinGate doesn't exist in python-sdk
